# Generated by Django 6.0.6 on 2026-06-15 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True)),
                ('descricao', models.TextField(blank=True, max_length=500, null=True, verbose_name='Descrição')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('quantidade_estoque', models.PositiveIntegerField(verbose_name='Quantidade em Estoque')),
                ('categoria', models.CharField(choices=[('Ração', 'Ração'), ('Brinquedo', 'Brinquedo'), ('Higiene', 'Higiene'), ('Medicamento', 'Medicamento'), ('Acessório', 'Acessório')], max_length=20, verbose_name='Categoria')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='pet',
            name='porte',
            field=models.CharField(choices=[('Pequeno', 'Pequeno'), ('Médio', 'Médio'), ('Grande', 'Grande')], default='Médio', max_length=10, verbose_name='Porte'),
        ),
        migrations.AddField(
            model_name='servico',
            name='categoria',
            field=models.CharField(choices=[('Estética', 'Estética'), ('Saúde', 'Saúde'), ('Hospedagem', 'Hospedagem'), ('Outros', 'Outros')], default='Outros', max_length=20, verbose_name='Categoria'),
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('hora', models.TimeField(verbose_name='Hora')),
                ('status', models.CharField(choices=[('Agendado', 'Agendado'), ('Realizado', 'Realizado'), ('Cancelado', 'Cancelado')], default='Agendado', max_length=10)),
                ('observacoes', models.TextField(blank=True, max_length=500, null=True, verbose_name='Observações')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos', to='core.funcionario', verbose_name='Funcionário')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos', to='core.pet')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos', to='core.servico', verbose_name='Serviço')),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
                'ordering': ['-data', '-hora'],
            },
        ),
    ]
